//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Pondskater.IO { 
/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
[System.Xml.Serialization.XmlRootAttribute("graphml", Namespace="http://graphml.graphdrawing.org/xmlns", IsNullable=false)]
public partial class Graphml {
    
    private GraphmlKey[] keyField;
    
    private GraphmlGraph graphField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("key")]
    public GraphmlKey[] Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("graph")]
    public GraphmlGraph Graph {
        get {
            return this.graphField;
        }
        set {
            this.graphField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlKey {
    
    private double defaultField;
    
    private bool defaultFieldSpecified;
    
    private string attrnameField;
    
    private string attrtypeField;
    
    private string forField;
    
    private string idField;
    
    /// <observações/>
    public double @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultSpecified {
        get {
            return this.defaultFieldSpecified;
        }
        set {
            this.defaultFieldSpecified = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("attr.name")]
    public string Attrname {
        get {
            return this.attrnameField;
        }
        set {
            this.attrnameField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("attr.type")]
    public string Attrtype {
        get {
            return this.attrtypeField;
        }
        set {
            this.attrtypeField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("for")]
    public string @for {
        get {
            return this.forField;
        }
        set {
            this.forField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("id")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlGraph {
    
    private GraphmlGraphNode[] nodeField;
    
    private GraphmlGraphEdge[] edgeField;
    
    private string edgedefaultField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("node")]
    public GraphmlGraphNode[] Node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("edge")]
    public GraphmlGraphEdge[] Edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("edgedefault")]
    public string Edgedefault {
        get {
            return this.edgedefaultField;
        }
        set {
            this.edgedefaultField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlGraphNode {
    
    private GraphmlGraphNodeData[] dataField;
    
    //Should the id field be int?
    private string idField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("data")]
    public GraphmlGraphNodeData[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("id")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlGraphNodeData {
    
    private string keyField;

    private string valueField;
    //private double valueField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("key")]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlGraphEdge {
    
    private GraphmlGraphEdgeData dataField;
    
    private string sourceField;
    
    private string targetField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlElementAttribute("data")]
    public GraphmlGraphEdgeData Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("source")]
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("target")]
    public string Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <observações/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://graphml.graphdrawing.org/xmlns")]
public partial class GraphmlGraphEdgeData {
    
    private string keyField;
    
    private double valueField;
    
    /// <observações/>
    [System.Xml.Serialization.XmlAttributeAttribute("key")]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
}